name: Build and publish documentation

on:
  push:
    branches: [ main ]

  # allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.0'
      - run: mix deps.get
      - run: mix compile
      - name: Cache dependencies and build output
        uses: actions/cache@v2.1.6
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix docs -f html
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: doc
