name: Run integration tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  # allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.0'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - name: Cache dependencies and build output
        uses: actions/cache@v2.1.6
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Run tests
        env:
          MIX_ENV: test
        run: |
          chromedriver &
          mix test
